// Interceptor implementations - MODIFY THIS FILE!
// Auto-generated by scripts/generate_layer.py
// Re-generating will overwrite this file - make backups of your changes!

#include "layer_config.h"
#include "layer.h"
#include <openxr/openxr.h>

// Auto-generated interceptor implementations

XRAPI_ATTR XrResult XRAPI_CALL layer_xrGetSystem(XrInstance instance, const XrSystemGetInfo * getInfo, XrSystemId * systemId) {

	return g_context.xrGetSystem(instance, getInfo, systemId);
}

XRAPI_ATTR XrResult XRAPI_CALL layer_xrCreateSession(XrInstance instance, const XrSessionCreateInfo * createInfo, XrSession * session) {

	return g_context.xrCreateSession(instance, createInfo, session);
}
